name = "B Function"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "B Function_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "B Function.wasm"
command = "npm run build:release"
